### ISSUE TITLE
Refactor intra-microfrontend communication

### ISSUE THREAD

**Issue by cristiano-belloni** [cristiano-belloni/modular-microfrontends#3]
Using multiple instances of [Broadcast Channel](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API)  works and gets rid of the `broadcast` field but has an order / registration issue.

**Comment by steveukx** [comment]
The use of `postMessage` is a bit basic, but the grid/card view start order shouldn't impact the ability to receive messages:

https://user-images.githubusercontent.com/221809/199797726-e3b9a12e-46c8-462d-ae03-8a0101cce2ea.mov

**Comment by cristiano-belloni** [comment]
@steveukx You're right, I didn't rebuild after testing Broadcast Channel - my fault; I changed this ticket to research a way to use BC without needing a precise order (or, more probably, I just need to implement BC comms correctly)
